### ISSUE TITLE
problem redirecting to the same page while posting a comment

### ISSUE THREAD

**Issue by aditiprasad** [aditiprasad/Forum#2]
Hey anna! my code breaks each time i try to post a comment and redirect it to the same page. it says thread in 'thread.title' is undefined. but if i redirect it to the root, everything works. 
this is my code:

```
app.post("/threads/:thread_id/comments", function(req, res){
    db.get("SELECT id FROM threads", function(error, row){
        var threadId = row.id
        if(error){
            console.log(error);
        } else {
                var userName = req.body.user_name_comment;
                var entry = req.body.entry;
            db.run("INSERT INTO comments (entry, user_name_comment, thread_id) VALUES (?,?,?)", entry, userName, threadId, function(error){
                if(error){
                    console.log(error);
                } else {

                    res.send("/threads/:id");
                }
            })
        }
    })
})
```

this is my show html : 

```
<html>
<head>
    <title></title>
</head>
<body> 
    <div>
        <h1> Thread - <%= thread.title %> </h1>
        <h4> Posted by <%= thread.user_name_thread %> </h4> 
<!--         <form method="POST" action="/threads">
            <input type="checkbox" name="likes" value="Like">
        </form> -->
    </div>
<div>
   <% comments.forEach(function(element){ %>
   <h2><%= element.user_name_comment %>: </h3>
   <h4> <%= element.entry %> </h4>
<% }) %>
</div>

    <div>
     <form method="POST" action="/threads/:thread_id/comments">
       <fieldset>
        <legend>Comments</legend>
        <input type="text" name="user_name_comment" placeholder="User Name">
        <TEXTAREA name="entry"></TEXTAREA>
        <input type="submit" value="Add Comment"
       </fieldset>
     </form> 
    </div>
</body>
</html>
```

**Comment by aditiprasad** [comment]
haha never mind. i got it to work

**Comment by annarankin** [comment]
Hey Aditi! Your problem is with your res.send - you need to send your user to /threads/7 or like threads/8 instead of threads/:id.

**Comment by annarankin** [comment]
Aha! Glad you fixed it lol

**Comment by aditiprasad** [comment]
oh no wait. it doesn't work :\

**Comment by aditiprasad** [comment]
but anna i want them to go back to whichever page that they posted their comment on. if i specify 7 then they'll be only sent to that specific thread with an id of 7 right?

**Comment by annarankin** [comment]
Orrrrr you could send them to "/threads/" + req.params.thread_id

**Comment by aditiprasad** [comment]
that doesn't seem to work either :( it's giving me same the same error as before, only now it says that 'title' is undefined in my ejs

**Comment by aditiprasad** [comment]
```
app.get("/threads/:id", function(req, res){
    // console.log(req.params);
    var id = req.params.id;
    db.get("SELECT * FROM threads WHERE id=?", id, function(error, row){
        console.log()
        var thread = row;
        if(error){
            console.log(error);
        } else {
            db.all("SELECT * FROM comments WHERE thread_id=?", id, function(error, row){
                if(error){
                    console.log(error);
                } else {
                    var comments = row;
                    var template = fs.readFileSync("views/show.html", "utf8");
                    var rendered = ejs.render(template, {thread : thread, comments : comments});
                    res.send(rendered);
                }
            })

        }
    })
});
```

**Comment by aditiprasad** [comment]
this is my code for getting the thread

**Comment by annarankin** [comment]
Oh also res.redirect not res.send

**Comment by aditiprasad** [comment]
oh yes i changed that

**Comment by aditiprasad** [comment]
still doesn't work

**Comment by annarankin** [comment]
Hmm I'm out right now and not at my computer, can you make sure you commit
and push your code up to github so I can take a look when I get home?

**Comment by aditiprasad** [comment]
i'll do that :)

**Comment by annarankin** [comment]
Hey Aditi! I don't see anything in this repo - is it set up?

**Comment by aditiprasad** [comment]
I just did Anna

**Comment by annarankin** [comment]
Good morning Aditi! I cloned down your repo - it works if I change line 90 to: `res.redirect("/threads/"+threadId);`

When you're `res.redirect`ing, you're not telling the server to go to a certain function - you're telling the user's browser to go to a specific URL. By including the variable you already have available in your `post` function instead of using `/threads/:thread_id/`, you can send the user back to where they came!

**Comment by aditiprasad** [comment]
Haha sorry Anna, i forgot to update you. I got it to work today morning. Should have closed the issue.
